# Generated by Django 3.1.4 on 2021-01-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='eductation',
        ),
        migrations.AddField(
            model_name='profile',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='helpers.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Not set', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpers.sessionyearmodel'),
        ),
    ]
