# Generated by Django 3.1.4 on 2021-01-03 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('students', '0002_auto_20210102_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.sessionyearmodel'),
        ),
    ]
