# Generated by Django 3.1.4 on 2021-01-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('students', '0003_auto_20210103_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helpers.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpers.sessionyearmodel'),
        ),
    ]
