# Generated by Django 3.1.4 on 2021-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210103_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
